//
//  Constants.swift
//  Constants
//
//  Created by Mind on 10/09/21.
//

import Foundation

let kHomeButtonTitle = "Present Bottom Sheet"
let kPlaceholderText: String = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. In dictum non consectetur a erat nam at. Tincidunt augue interdum velit euismod in pellentesque massa. Suscipit tellus mauris a diam maecenas sed enim ut. Vitae justo eget magna fermentum iaculis eu non diam. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Pellentesque nec nam aliquam sem et tortor consequat. Id porta nibh venenatis cras sed. Mi quis hendrerit dolor magna eget est lorem ipsum dolor. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Vivamus arcu felis bibendum ut. Elit ullamcorper dignissim cras tincidunt lobortis. Sit amet luctus venenatis lectus magna. Tempor commodo ullamcorper a lacus vestibulum sed. Nec ultrices dui sapien eget mi proin sed. Volutpat maecenas volutpat blandit aliquam etiam erat. Duis convallis convallis tellus id. Sit amet est placerat in egestas erat imperdiet. Est velit egestas dui id ornare arcu odio ut.

Vitae semper quis lectus nulla. Lorem ipsum dolor sit amet consectetur adipiscing. Risus nec feugiat in fermentum. Auctor eu augue ut lectus. A pellentesque sit amet porttitor eget dolor. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Ut tristique et egestas quis ipsum suspendisse ultrices. Sed nisi lacus sed viverra tellus in hac. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Viverra aliquet eget sit amet tellus cras adipiscing enim. Lectus vestibulum mattis ullamcorper velit sed. Tincidunt vitae semper quis lectus. Faucibus nisl tincidunt eget nullam non nisi est sit. Risus nec feugiat in fermentum posuere urna nec. Egestas dui id ornare arcu odio ut sem nulla pharetra. At risus viverra adipiscing at. Risus sed vulputate odio ut enim blandit volutpat maecenas. Arcu felis bibendum ut tristique.

Eleifend quam adipiscing vitae proin sagittis nisl. A lacus vestibulum sed arcu non odio euismod lacinia. Adipiscing tristique risus nec feugiat in fermentum posuere. Turpis egestas maecenas pharetra convallis posuere morbi leo urna molestie. Enim sit amet venenatis urna cursus. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Velit dignissim sodales ut eu sem integer vitae justo. Ultrices sagittis orci a scelerisque purus semper. Vitae tortor condimentum lacinia quis vel. Netus et malesuada fames ac. Tincidunt ornare massa eget egestas purus viverra accumsan in nisl. Neque egestas congue quisque egestas diam in arcu cursus. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi.

Volutpat sed cras ornare arcu. Vitae tempus quam pellentesque nec nam. Et netus et malesuada fames ac turpis egestas sed tempus. Fringilla phasellus faucibus scelerisque eleifend donec. Sed lectus vestibulum mattis ullamcorper velit sed. Varius morbi enim nunc faucibus. Vulputate ut pharetra sit amet. Congue eu consequat ac felis donec et odio pellentesque. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Nec nam aliquam sem et tortor. Aliquet nibh praesent tristique magna sit. Orci phasellus egestas tellus rutrum. Leo urna molestie at elementum eu facilisis. Eget felis eget nunc lobortis mattis aliquam. Fermentum et sollicitudin ac orci phasellus egestas. Blandit aliquam etiam erat velit scelerisque in dictum.

Eget gravida cum sociis natoque penatibus et magnis dis. Dignissim sodales ut eu sem integer vitae justo eget. Feugiat in fermentum posuere urna. Amet tellus cras adipiscing enim eu turpis egestas. Urna id volutpat lacus laoreet non curabitur gravida arcu. Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Donec adipiscing tristique risus nec. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Fermentum et sollicitudin ac orci phasellus. Turpis massa sed elementum tempus egestas sed sed risus. Eget felis eget nunc lobortis. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et.
"""
